"use client";

import React, { useState } from "react";
import { useProjectStore } from "@/store/project-store";
import {
  Globe,
  RefreshCw,
  ExternalLink,
  Smartphone,
  Tablet,
  Monitor,
  ArrowLeft,
  ArrowRight,
} from "lucide-react";
import { cn } from "@/lib/utils";

type ViewportSize = "mobile" | "tablet" | "desktop";

const viewportWidths: Record<ViewportSize, string> = {
  mobile: "375px",
  tablet: "768px",
  desktop: "100%",
};

export function PreviewPanel() {
  const project = useProjectStore((s) => s.project);
  const previewUrl = useProjectStore((s) => s.previewUrl);
  const setPreviewUrl = useProjectStore((s) => s.setPreviewUrl);
  const [viewport, setViewport] = useState<ViewportSize>("desktop");
  const [urlInput, setUrlInput] = useState(previewUrl || "");
  const [key, setKey] = useState(0);

  // Generate a live preview from HTML files
  const htmlFile = project?.files.find(
    (f) => f.path.endsWith(".html") || f.path.endsWith("page.tsx")
  );

  const generatePreviewHtml = (): string => {
    if (!project?.files.length) return "";

    // Collect CSS
    const cssFiles = project.files.filter((f) => f.language === "css");
    const css = cssFiles.map((f) => f.content).join("\n");

    // Check for an HTML file first
    if (htmlFile?.language === "html") {
      return htmlFile.content;
    }

    // Generate a simple preview from available files
    const fileList = project.files
      .map(
        (f) =>
          `<div style="padding:8px 12px;border-bottom:1px solid #1e1e2e;font-family:monospace;font-size:13px;">
            <span style="color:#6366f1;">${f.path}</span>
            <span style="color:#64748b;margin-left:12px;">${f.content.split("\\n").length} lines</span>
          </div>`
      )
      .join("");

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0a0a0f;
      color: #e2e8f0;
      font-family: Inter, system-ui, sans-serif;
    }
    .header {
      padding: 24px;
      border-bottom: 1px solid #1e1e2e;
      background: #12121a;
    }
    .header h1 {
      font-size: 20px;
      font-weight: 700;
      background: linear-gradient(135deg, #6366f1, #a78bfa);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .header p {
      font-size: 12px;
      color: #64748b;
      margin-top: 4px;
    }
    .stats {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      padding: 16px 24px;
    }
    .stat {
      background: #12121a;
      border: 1px solid #1e1e2e;
      border-radius: 8px;
      padding: 16px;
    }
    .stat-value {
      font-size: 24px;
      font-weight: 700;
      color: #6366f1;
    }
    .stat-label {
      font-size: 11px;
      color: #64748b;
      margin-top: 4px;
    }
    .file-list { padding: 0 24px 24px; }
    .file-list h2 {
      font-size: 14px;
      font-weight: 600;
      padding: 12px 0;
      color: #64748b;
    }
    ${css}
  </style>
</head>
<body>
  <div class="header">
    <h1>${project.name}</h1>
    <p>Generated by SoloCoder | ${project.files.length} files</p>
  </div>
  <div class="stats">
    <div class="stat">
      <div class="stat-value">${project.files.length}</div>
      <div class="stat-label">Files Generated</div>
    </div>
    <div class="stat">
      <div class="stat-value">${project.files.reduce((s, f) => s + f.content.split("\\n").length, 0)}</div>
      <div class="stat-label">Lines of Code</div>
    </div>
    <div class="stat">
      <div class="stat-value">${project.plan?.tasks.filter((t) => t.status === "completed").length || 0}</div>
      <div class="stat-label">Tasks Complete</div>
    </div>
  </div>
  <div class="file-list">
    <h2>PROJECT FILES</h2>
    ${fileList}
  </div>
</body>
</html>`;
  };

  const handleRefresh = () => setKey((k) => k + 1);

  return (
    <div className="h-full flex flex-col bg-solo-terminal">
      {/* Toolbar */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-solo-border flex-shrink-0">
        {/* Navigation */}
        <button className="btn-ghost p-1" disabled>
          <ArrowLeft className="w-3.5 h-3.5" />
        </button>
        <button className="btn-ghost p-1" disabled>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
        <button onClick={handleRefresh} className="btn-ghost p-1">
          <RefreshCw className="w-3.5 h-3.5" />
        </button>

        {/* URL bar */}
        <div className="flex-1 flex items-center bg-solo-surface border border-solo-border rounded-md px-3 py-1">
          <Globe className="w-3.5 h-3.5 text-solo-text-muted mr-2 flex-shrink-0" />
          <input
            type="text"
            className="flex-1 bg-transparent text-xs text-solo-text-dim outline-none"
            value={urlInput}
            onChange={(e) => setUrlInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") setPreviewUrl(urlInput);
            }}
            placeholder="Enter URL or use generated preview"
          />
        </div>

        {/* Viewport toggles */}
        <div className="flex items-center gap-0.5 bg-solo-surface rounded-md border border-solo-border p-0.5">
          {([
            { size: "mobile" as const, icon: Smartphone },
            { size: "tablet" as const, icon: Tablet },
            { size: "desktop" as const, icon: Monitor },
          ]).map(({ size, icon: Icon }) => (
            <button
              key={size}
              onClick={() => setViewport(size)}
              className={cn(
                "p-1 rounded transition-colors",
                viewport === size
                  ? "bg-solo-accent text-white"
                  : "text-solo-text-muted hover:text-solo-text"
              )}
            >
              <Icon className="w-3.5 h-3.5" />
            </button>
          ))}
        </div>

        {previewUrl && (
          <a
            href={previewUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-ghost p-1"
          >
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        )}
      </div>

      {/* Preview area */}
      <div className="flex-1 flex items-start justify-center overflow-auto p-4 bg-solo-bg/50">
        {previewUrl ? (
          <iframe
            key={key}
            src={previewUrl}
            className="bg-white rounded-lg shadow-xl"
            style={{
              width: viewportWidths[viewport],
              height: "100%",
              maxWidth: "100%",
              border: "1px solid var(--solo-border)",
            }}
            sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
            title="Preview"
          />
        ) : project?.files.length ? (
          <iframe
            key={key}
            srcDoc={generatePreviewHtml()}
            className="rounded-lg shadow-xl"
            style={{
              width: viewportWidths[viewport],
              height: "100%",
              maxWidth: "100%",
              border: "1px solid #1e1e2e",
            }}
            sandbox="allow-scripts"
            title="Preview"
          />
        ) : (
          <div className="flex flex-col items-center justify-center gap-4 h-full">
            <Globe className="w-12 h-12 text-solo-border" />
            <div className="text-center">
              <p className="text-solo-text-dim text-sm">No preview available</p>
              <p className="text-solo-text-muted text-xs mt-1">
                Preview will be generated once files are created
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
